@startuml
'https://plantuml.com/class-diagram

class HTMLStrings {
String lines1-9;
+ changeLine4
+ changeLine5
+ print HTML
}

class websiteGenerator {
String siteName
String author
char javaConfirm
char CSSConfirm
String path
+ createHTMLFile()
+ createJavaFile()
+ createCSSFile()
}

@enduml